### ISSUE TITLE
Hay doesn't reset

### ISSUE THREAD

**Issue by turret001** [multitheftauto/mtasa-resources#346]
**Is your feature request related to a problem? Please describe.**
When a game of hay is over (player picks up the burger) it should teleport everyone down and re-create the burger pickup but it doesn't.

**Describe the solution you'd like**
It should teleport everyone down and re-create the burger pickup.

**Describe alternatives you've considered**
-

**Additional context**
I don't have any coding experience so I wasn't able to inspect the code but I've checked debugscript monitor while picking up the burger and nothing came up. However, there was an outputChatbox that was getting triggered when I picked up the burger, so script knows I won but it doesn't reset it. (or even if it does, it's not resetting fast enough.) I tried jumping down and respawning but no luck.

I have a test server set up, feel free to test at 195.174.168.123 (superman is added and should be available to everyone as well. just type /superman )

**Comment by Lpsd** [comment]
That was never coded in, when a player picks up the burger all it does is destroy the burger, send a message in chat declaring them the winner, then enables them to shoot (it used to be a minigun instead of a burger)

The code for that resource is a bit trash, without some cleanup the easiest way right now would be to simply restart the resource (using `restartResource`) after this line https://github.com/multitheftauto/mtasa-resources/blob/d208b13649abeb46afc7d59a0f0cfe6265691610/%5Bgamemodes%5D/%5Bhay%5D/hay/Hay.lua#L223

All the init stuff is done inline, directly when the script loads, that needs moving into a function of its own. There's also no function currently to "reset" the round and ensure previous stuff / memory is cleaned up.

**Comment by Dutchman101** [comment]
Hay (just like Fallout) is 1 of the most iconic gamemodes of MTA, especially in the early years. So that's why i feel it deserves a rewrite..

**Comment by turret001** [comment]
I don't know about a rewrite but it definitely needs to be updated to work better

**Comment by jlillis** [comment]
I had started some refactoring work a long time ago but didn't think there was any interest in reviving this gamemode and moved on to other items. Since it appears there is, I'll see if I can crank out a PR in the next week or two.

**Comment by Dark-Dragon** [comment]
Since the large refactor seems not to be happening, I propose just basic round restarting as the new goal..? Would #420 suffice?

**Comment by jlillis** [comment]
Forgot about this... I had started some work to rewrite the resource but then got busy with work. Not really interested in getting started on this again at the moment. I think making some quick fixes would be great.

**Comment by MegadreamsBE** [comment]
I'd honestly be happy to give rewriting it a shot since it'd be a nice break from my usual work and hay is very iconic gamemode. Would be nice to figure out if there's any changes we'd like to have as part of the rewrite though.

**Comment by MegadreamsBE** [comment]
Yeah, I think I'm going to commit to the rewrite. I pretty much have the entire base finished (spawning of the players, hay bales and rocks are spawned and hay bales move in a similar fashion to old hay. Also spawning in the pickup already, just need to update the scoreboard, show some info like old hay on the right side and write the logic for the game to end.

I'm making the code base easier to work with and more reusable. It's easy due to the way I've written it to reset the gamemode without having to restart the resource.

**Comment by jlillis** [comment]
I don't remember playing hay with the minigun at the top so no comment.

I had a short list of things I was looking to do with hay you might consider:
1: Use EDF to allow custom hay mode maps. Can have multiple stacks, each customizable in element settings.
2: Integrate more with other resources to reduce bloat - mapcycler/mapmanager, missiontimer, spawnmanager, etc.
3: Singleplayer themed UI (easy)

Points 2 and 3 should be easy. I was having trouble setting up the EDF stuff in a way that works well within the editor - particularly, the ability to visualize the haystack once placed.
