### ISSUE TITLE
Resourcemanager is broken

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-resources#358]
**Which resource(s) have this problem?**
resourcemanager

**Describe the bug**
Resourcemanager stopped working after browser update

**To Reproduce**
Download latest resources

**Screenshots**
https://i.imgur.com/w9QAY0z.png

**Version**
Latest resource pack + Chrome 95.0.4638.54 / Tested also on latest firefox, not working

**Comment by ArranTuna** [comment]
I have latest resources and not getting any errors when restarting it:

![image](https://user-images.githubusercontent.com/253404/142212690-05b19d8c-09e8-4551-84f1-0bbfbfb30ac3.png)

**Comment by iDannz1** [comment]
I was going to create a new issue about this bug right now but just found this one....

@ArranTuna steps to reproduce:
1. start the resource `resourcemanager`.
2. go to http://localhost:[http-port]/resourcebrowser/.
3. select any resource in the list and see the server console.

I took a little look at the code and noticed that this is happening because the [getResourceInfo](https://github.com/multitheftauto/mtasa-resources/blob/master/%5Bweb%5D/resourcemanager/manager.lua#L21) function expects a resource as parameter, but it's receiving a table with the keys `name` and `state`.

**Comment by Xenius97** [comment]
Something is broken in javascript, sorry I didn't see your answer Arran, didn't get email.
Select a resource, and you can't even do anything because of these error.

**Comment by ArranTuna** [comment]
I've fixed it. I guess at some point some code change some where (unless it never worked to begin with) caused a behaviour change that broke this. If you pass a resource userdata like getResourceFromName("acpanel") javascript receives {"name":"acpanel"} instead of a userdata but this script acted as if the resourcedata was passed correctly but then it also seems to use this .name thing so I dunno it's weird, but everything works now so yeah...
