### ISSUE TITLE
Making MTA easier for the community and easier to be Creative on

### ISSUE THREAD

**Issue by CarlRayanitch** [multitheftauto/mtasa-resources#409]
many people have great ideas that would get more players and make them stay 24/7 in MTA but sadly most of us don't know how to script, It would be a great idea to develop mta in a way like Roblox Studio in Map Editor, adding a spawn to place and many things even like graphical stuff if this item should have a shadow or not. Map Editor would be the engine of the game rather than creating notepads for every single script then joining the server and starting the resource to test if it works or not which is too stressful and i would even bother learning how to script. Doing this change in the MTA 1.6 version would flip the whole game

**Comment by F2BShady** [comment]
yes, your opinion is good and I have something to say. On the MAP Editor side, we need a map editor that we can develop better and more in a simpler and better way.

Must see what MTA players can do,everyone's brain works great and innovations are needed.

**Comment by PlatinMTA** [comment]
If you want to create something nicer, you need to learn how to program. The same with moddeling, mapping or every other aspect of the game.

You should check the https://community.multitheftauto.com/ and search for some resources or gamemodes. Then try to edit the files a little bit. The easier and more straight-forward the script the better, otherwise you might not understand a thing or it can be bloated af.

**Comment by Fernando-A-Rocha** [comment]
Using Point & Click and Drag & Drop to create game modes/scenarios would be really fun because it does enable people who aren't into programming (a huge percentage of mta players and server owners) to make create usable scripts for their server without writing a single line of code.

I imagine that we could have such a "studio" resource that lets you generate a variety of dynamic scripts.

I can see this being like Scratch where you use simple condition blocks and trigger events, etc, all with a nice interface and visual feedback.

I'm in favor of discussing this to see what we can come up with.

**Comment by F2BShady** [comment]
> I can see this being like Scratch where you use simple condition blocks and trigger events, etc, all with a nice interface and visual feedback.

yes that's what we're talking about, it feels so good to dream of something like this

**Comment by PlatinMTA** [comment]
It can be created but because of the nature of MTA I think it would be quite hard to achieve.

We have the neccesary functions to create resources without actually needing to change any file, with:

https://wiki.multitheftauto.com/wiki/CreateResource
https://wiki.multitheftauto.com/wiki/CopyResource
https://wiki.multitheftauto.com/wiki/DeleteResource
https://wiki.multitheftauto.com/wiki/RefreshResources

For GUIs you actually already have a tool, called ``guieditor``. It's been out since forever at this point.

The problem's start with things like finding files, most people would want to have their own files used, be it mods, images, sounds, etc. That's the first issue with something like this. MTA does not have any way of reading folders outside the resources, hence, you need to navigate to those 'obscure' folders (something like ``MTA San Andreas 1.5/server/mods/deathmatch/[editor]/scratch``).

Other problems will include most likely performance issues, it's really easy to make MTA struggle, at least clientside, which is easier to fix manually, but not so much automatically. Depending on the level of depth the editor has I don't know how much worth it would it be.

___

If you need to do something like:

_onClientElementStreamIn -> addEvent onRender -> onRender: draw X thing
onClientElementStreamOut -> if event onRender exists -> remove event_

in order to draw a single text, then it's not worth it

___

It should probably look more like this:

_Is element streamed -> showText_

And it should automatically do the code for you in the best way possible. Otherwise you would be better of just learning to code because you will need to do it one way or the other.

**Comment by Fernando-A-Rocha** [comment]
@PlatinMTA Yeah well said, it seems very complicated, but such a system could be attempted incrementally, from very basic to complex; doesn't need to be made in one go.

You reminded me that this [suggestion](https://github.com/multitheftauto/mtasa-blue/issues/2489) should be made into MTA and it would fix the problem of sending files from the client to a server.

Back on topic though, we have official resources for almost everything including "admin" for managing players and the resources themselves, "editor" for creating maps, and plenty of premade game modes that are a bit dated already.

What we indeed don't have is a tool to create game modes / missions / scenarios etc. This can be explored imo.

**Comment by jlillis** [comment]
I don't think there exists enough manpower within the official resources team to develop, review, and support an official in-game development environment like Scratch or Roblox Studio. Frankly, I don't think this is something that would be worth the effort given the relative ease of Lua scripting in MTA - the barrier to entry is very low (compared to other video game modding ecosystems, and IMO) and we should encourage and support people to learn scripting instead.

There is progress that can be made with regard to improvements to the map editor. We should consider:
- Integration of popular community add-ons for the editor. Some that come to mine are the various tools race map authors use to generate loops and other cool features that do not exist by default.
- The ability to place and manipulate blips, colshapes, effects, radar areas, and water elements within the editor as default functionality (#262, #388)
- Ability to replace textures (#233), and replace models (or define new ones).
- Further improvements to the EDF framework (especially documentation) to encourage gamemode and resource authors to utilize them. This framework allows scripters to extend the functionality of the editor for use with their scripts & resources, but adoption appears to be low. The default resources and gamemodes make use of this - to place spawnpoints, race checkpoints, and more. A lot of cool functionality is only known to the few of us who dig into the code and know how to make certain things work.

I would also recommend reaching out to the author/maintainers of `guieditor` and see if they would allow us to include it as a default resource.
